## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Böimig Baumig"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params.social]
  email = "boeimigbaumig@gmail.com"